name = "CovidPOMDP"
uuid = "4873485c-d2fa-4361-8bce-f1ee1b7602e1"
authors = ["WhiffleFish <tylertronics@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
